include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
- test
- deploy

variables:
    GIT_SUBMODULE_STRATEGY: normal

flatpak:master:
    extends: .flatpak
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    stage: test
    variables:
        BUNDLE: "sound-juicer-dev.flatpak"
        MANIFEST_PATH: "build-aux/org.gnome.SoundJuicer.json"
        MESON_ARGS: "-Dprofile=development"
        FLATPAK_MODULE: "sound-juicer"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        APP_ID: "org.gnome.SoundJuicer"
    extends: .flatpak

review:
    extends: .review
    stage: deploy
    dependencies:
        - flatpak:master

stop_review:
    extends: .stop_review
    stage: deploy

nightly:
    extends: '.publish_nightly'
