.\" Copyright (C) 2006 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH sound-juicer 1 "2006\-11\-26" "GNOME"
.SH NAME
sound-juicer \- GNOME-desktop CD ripper and player using GStreamer
.SH SYNOPSIS
.B sound-juicer
.RI [ option... ]
.SH DESCRIPTION
.B sound-juicer
is a CD ripper and player for GNOME which aims to have a simple, clean, easy to use interface.
.B sound-juicer 
supports encoding to several popular audio formats such as Ogg Vorbis and FLAC, additional formats can be added through GStreamer plugins.
.P
For additional documentation on interactive use of 
.B sound-juicer
select the
.I Help
menu option. The menus allow access to features not available through command-line options.
.SH OPTIONS
.TP
.B \-a, \-\-auto-start
Start extracting immediately
.TP
.B \-p, \-\-play
Start playing immediately
.TP
.B \-d, \-\-device=DEVICE
What CD device to read
.TP
.B \-\-display=DISPLAY
X display to use
.TP
.B \-?, \-\-help
Show help options
.TP
.B \-\-help-all
Show all help options
.TP
.B \-\-help-gst
Show GStreamer Options
.TP
.B \-\-help-gtk
Show GTK+ Options
.TP
.B \-\-help-bonobo-activation
Show Bonobo Activation options
.TP
.B \-\-help-gnome
Show GNOME options
.TP
.B \-\-help-gnome-session
Show session management options
.TP
.B \-\-help-gnome-ui
Show GNOME GUI options

.SH AUTHOR
.B sound-juicer
was written by Ross Burton <ross@burtonini.com>.
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian GNU/Linux system (but may be used by others).
.SH SEE ALSO
The online documentation available through the program's
.I Help
menu.


